on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run conversion script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Configure Git
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"

      - name: Commit HTML files to gh-pages
        run: |
          git add .
          git commit -m "Build $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages
