name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run build script
        run: bash ./scripts/build.sh ./markdown ./build -css ./public/global.css

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-artifact
          path: ./build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: github-pages-artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          publish_dir: ./build/
